# netlify.toml
[functions]
  directory = "functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://freerider.app"
    Access-Control-Allow-Origin = "http://127.0.0.1:5500/"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"